### ISSUE TITLE
Error No such table

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [prooph/event-store#353]
Hi all, I have a problem with my first project in prooph.
When I save an event I get this error:

````
SQLSTATE[HY000]: General error: 1 no such table: _4228e4a00331b5d5e751db0481828e22a2c3c8ef
```

I have configured this persistence strategy:

```
services:
    Prooph\EventStore\Pdo\MySqlEventStore:
        arguments: ['@prooph_event_store.message_factory', '@doctrine.pdo.connection', '@prooph_event_store.single_stream_strategy']

    doctrine.pdo.connection:
        class: PDO
        factory: ['@database_connection', getWrappedConnection]

    prooph_event_store.single_stream_strategy:
        class: Prooph\EventStore\Pdo\PersistenceStrategy\MySqlSingleStreamStrategy

    prooph_event_sourcing.aggregate_translator:
        class: **Prooph\EventSourcing\EventStoreIntegration\AggregateTranslator**
```

I'm sure that I have lost something, so I have tried to launch this command taken from a prooph project:

```
bin/console event-store:event-stream:create
```

it creates into the database into event_stream table the right record and into stream_name there is the same string of my error because is converted with sha1 I have seen

_4228e4a00331b5d5e751db0481828e22a2c3c8ef

What can I do?
